[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "18" # You can adjust this to match your Node.js version

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable Netlify Edge Functions
[functions]
  directory = "netlify/functions"

# Enable Netlify Blobs for data persistence
[[edge_functions]]
  function = "visitor-count"
  path = "/.netlify/functions/visitor-count"