[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18" # You can adjust this to match your Node.js version

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200