[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18" # You can adjust this to match your Node.js version

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configure Edge Functions for the visitor counter
[[edge_functions]]
  path = "/api/visitor-count"
  function = "visitor-count"

[blobs]
  serve_origin = "visitor-count"