name: Trigger Netlify Build

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes
  workflow_dispatch:  # allows you to manually trigger it too

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build Hook
        run: curl -X POST https://api.netlify.com/build_hooks/68036a5bb3d6a3f122a2db3f
